image: php:7.4-apache
services:
  - name: mysql:5.7
    alias: mysql
variables:
  MYSQL_ROOT_PASSWORD: db_password
  MYSQL_DATABASE: db_name
  MYSQL_USER: db_user
  MYSQL_PASSWORD: db_password
  DATABASE_URL: "mysql://db_user:db_password@mysql:3306/db_name"
cache:
  paths:
    - vendor/
before_script:
  - apt-get update && apt-get install -y git libzip-dev
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install
  - docker-php-ext-install mysqli pdo pdo_mysql zip
test:
  script:
    - php bin/phpunit
