language: php
cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/symfony-bridge/.phpunit
warnings_are_errors: false
services:
    - mysql
php:
    - 7.4.27
install:
    - composer install --prefer-dist --no-interaction --ignore-platform-reqs
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:update --force --env=test
    - php bin/console doctrine:fixtures:load -n --env=test
script:
    - php bin/phpunit --coverage-text --colors
